### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by leonm1** [aadibajpai/university#2]
Seems cool and all, and I imagine that you match against a list of known IPs, but I can't tell if you actually do that or not because the source file is missing from this repo. Is that intentional or is this FLOSS?

**Comment by siraben** [comment]
It would be good if the source code for the web worker were released as well since the code in the repo is just an API call.

**Comment by ragasirtahk** [comment]
I concur.

**Comment by sayyss** [comment]
Petition to release the backend code.

**Comment by FadedCoder** [comment]
I doth concur-eth

**Comment by aadibajpai** [comment]
> Seems cool and all, and I imagine that you match against a list of known IPs, but I can't tell if you actually do that or not because the source file is missing from this repo. Is that intentional or is this FLOSS?

Well we're not actually doing that—the actual method is much simpler. 

There's a fair case for open sourcing it, there's a couple of reasons it's not:
The code is in a CF worker so would need to adjust deployment to be from the repo.
I think I'm also somewhat hesitant to open the worker sauce since then it's not fun anymore once you see how simple it is, whereas right now there's a clear interest in the mystery as evident from this issue 😈

**Comment by FadedCoder** [comment]
> > Seems cool and all, and I imagine that you match against a list of known IPs, but I can't tell if you actually do that or not because the source file is missing from this repo. Is that intentional or is this FLOSS?
> 
> Well we're not actually doing that—the actual method is much simpler.
> 
> There's a fair case for open sourcing it, there's a couple of reasons it's not:
> The code is in a CF worker so would need to adjust deployment to be from the repo.
> I think I'm also somewhat hesitant to open the worker sauce since then it's not fun anymore once you see how simple it is, whereas right now there's a clear interest in the mystery as evident from this issue 😈

Concur doth i,
F'r if 't be true this wast open sourcedeth,
And people couldst marvel upon t's simplicity,
T wouldn't beest excit'ment anym're.

**Comment by aadibajpai** [comment]
> > > Seems cool and all, and I imagine that you match against a list of known IPs, but I can't tell if you actually do that or not because the source file is missing from this repo. Is that intentional or is this FLOSS?
> > 
> > 
> > Well we're not actually doing that—the actual method is much simpler.
> > There's a fair case for open sourcing it, there's a couple of reasons it's not:
> > The code is in a CF worker so would need to adjust deployment to be from the repo.
> > I think I'm also somewhat hesitant to open the worker sauce since then it's not fun anymore once you see how simple it is, whereas right now there's a clear interest in the mystery as evident from this issue 😈
> 
> Concur doth i,
> F'r if 't be true this wast open sourcedeth,
> And people couldst marvel upon t's simplicity,
> T wouldn't beest excit'ment anym're.
> 
> On another note, I want corona go shoo shoo, I wanna use dis at my uni too :<

ok wait one sec

**Comment by aadibajpai** [comment]
https://github.com/aadibajpai/university-worker y'all won me over
